### ISSUE TITLE
No Direct Deposit payment info on checkout

### ISSUE THREAD

**Issue by Redshift-Web-Design** [NetoECommerce/Skeletal#105]
Testing with latest Skeletal
If you select Direct Deposit payment method it used to show this block

<div ref="bank" class="_cpy_paydesc alert alert-info"> Our bank details will be provided after you confirm your order below. </div>

Not anymore....

**Comment by ryvanvel** [comment]
Hey guys,

We've investigated this and it appears to be an issue with Neto triggering the appropriate div for the method & a potential name mismatch - however since the release of managed checkout they won't be fixing this issue, because we call payment methods in an entirely new way which already solves this bug.

As such, we'll be closing this issue & recommend use of the managed checkout for your site.

**Comment by ryvanvel** [comment]
FYI though, if you want to patch it in your customised checkout, you can attach your own bit of JS on the dropdown & payment icon based on the unique `rel` attribute to show/hide the appropriate div below with the jquery show/hide functions.
