### ISSUE TITLE
List view thumbnails on mobile are broken

### ISSUE THREAD

**Issue by quatlin** [NetoECommerce/Skeletal#162]
![screen shot 2016-07-21 at 8 19 38 am](https://cloud.githubusercontent.com/assets/4051162/17005234/84840b34-4f1c-11e6-8eee-71834f1a4716.png)

List view isn't really relevant to mobile — should we remove entirely?

**Comment by philcon93** [comment]
Removing it completely wouldn't work for people who select list view as default

**Comment by brandonsheppard** [comment]
Looks like we just need to collapse it down to the next line

**Comment by ryvanvel** [comment]
Fixed in commit 3894b9c - This is just a fix, but I think Phil is halfway right - these thumbnails aren't great on mobile. The way I see it list templates are ideal for people with info-heavy products & lots of them, the mobile versions of this don't format that information well.

Going forward I'd recommend an enchancement to these, introduce some custom classes and make these far slicker for mobile, like single lines with just an image/link and smaller fonts for example.
