### ISSUE TITLE
Hide shipping calc from service items

### ISSUE THREAD

**Issue by robm2002** [NetoECommerce/Skeletal#211]
If the item is of type "service" (e.g. an electronic gift voucher) the shipping calculator is irrelevant, so should be hidden from the product page.

**Comment by readeral** [comment]
I'm curious, I have thoughts about this too (and a general solution in my situation, based on a custom product template and splitting the shipping calculator from buying_options.template.html into it's own ajax template) - but what do you mean by "If the item is of type "service""?

If you mean the 'type' field under 'other' on the product edit page, then it should be relatively easy to drop an [%if][%else] set of tags into the skeletal template to test that type field for 'service' and skip including the relevant ajax template. Otherwise, is there another way of setting a product type that you're hoping to utilise? If so, I'm interested to know what that is..

**Comment by philcon93** [comment]
You could definitely add some logic to the shipping calculator so it doesn't display for service type products. Possible data tags could be something like `[@product_type@] ` or `[@service_only@] `, or even create a product misc field which you can toggle per product. You would just add an AND to the if statement around the shipping calculator in the buying_options template.

We don't have this additional logic in skeletal because there isn't a dedicated data tag for this and we wouldn't want to use those other data tags as their prime use isn't for this situation.

Ideally, we could have a dedicated field in the product setup which could toggle this off on a product level, I would highly recommend submitting this as an idea to the product team with the following form:

- http://forms.neto.com.au/products/ideas.html

**Comment by readeral** [comment]
So what is the current purpose of the 'service' type in Neto at the moment?
