### ISSUE TITLE
Reviews icon for child product

### ISSUE THREAD

**Issue by mmwoods** [NetoECommerce/Skeletal#314]
The reviews stars within the product 'header' template return the parents number of reviews, from '[@reviews@]' when within a product which has children.

Needs to pull the review count from the child and not the parent.

**Comment by philcon93** [comment]
This is done this way by design; customers can not by default / easily review child products. The write a review button on product pages will always go to the parents write review page as it is on the main product page template. the only way a customer would be able to review a child product is with a direct url, which technically is possible with email marketing but with Skeletal it should stay referring the parent instead of a child. Parent products will have more reviews then children products.

**Comment by craigblunden** [comment]
Context of the problem should have been explained better perhaps with code examples. The problem isn't the review itself rather that the code is in correct and does not display on child/parent products.

**Comment by matt-downs** [comment]
Somewhat related to issue #303
