### ISSUE TITLE
Product page - Min/Max Multiplier

### ISSUE THREAD

**Issue by GerryFort** [NetoECommerce/Skeletal#396]
Hi there,

It appears that the min/max multiplier arrows no longer work?
Ie; for products in which need buying in lots of 2,5,10,20 etc - when pressing the UP/DOWN arrows it only increases by 1 rather than the specified [@multiplier_qty@]

I have a template in which this used to work, but it doesn't appear to work anymore?
Has this feature since been removed in the new skeletal?

Kind Regards,
Gerry

**Comment by GerryFort** [comment]
In reference to this code in custom.js

```
modQtyByMulti: function(obj,act) {
			var mul = 1;
			var maxm;
			var minm = 0;
			var objid = obj.replace(/^qty/,'');
			if ($('#qty'+objid).length > 0) {
				if ($('#multiplier_qty'+objid).length > 0) {
					mul = $('#multiplier_qty'+objid).val();
				}
				if ($('#min_qty'+objid).length > 0) {
					minm = $('#min_qty'+objid).val();
				}
				if ($('#max_qty'+objid).length > 0) {
					maxm = $('#max_qty'+objid).val();
				}

				var cur = $('#'+obj).val();
				var curmin = $('#'+obj).attr('min');
				if (isNaN(cur)) {
					cur = 0;
				}

				if (act == 'add') {
					cur = parseInt(cur) + parseInt(mul);
					if (!isNaN(maxm) && cur > maxm) {
						cur = maxm;
					}
				}
				else if (act == 'subtract') {
					cur = parseInt(cur) - parseInt(mul);
					if (cur < minm) {
						cur = minm;
					}
				}
				
				else if (act == 'addmin') {
					cur = parseInt(cur) + parseInt(curmin);
					if (!isNaN(maxm) && cur > maxm) {
						cur = maxm;
					}
				}
				
				else if (act == 'subtractmin') {
					if(cur > curmin){
						cur = parseInt(cur) - parseInt(curmin);
						if (cur < minm) {
							cur = minm;
						}
					}
				}

				$('#qty'+objid).val(cur);
			}
		}
```

particularly the act of addmin and subtractmin - they sometimes report back with a NaN value if the QTY input is left empty, and the QTY field becomes empty on products with children with no variations specified (the grid view) after clicking ADD TO CART; those fields become empty and should you go to add more, you get NaN values.

**Comment by philcon93** [comment]
Hey @GerryFort, the `modQtyByMulti ` function isn't used by default on Skeletal but is a helper function to use to enhance the product page functionality, I think the template you have had this implemented on might be done as a design tweak instead of standard Skeletal. If it was Skeletal, we could find it in this repo or in the commit history.

But this is great you bring this up, the functions in `custom.js` are not easy to understand and if a developer can use them or not. It would be interesting to see if this functionality could be added in to Skeletal without causing issues for products that don't use min/max/multiplier. Also documentation on these functions would greatly help developers understanding of them.

**Comment by GerryFort** [comment]
Thanks Phil. I was told that this was a tweak done by Neto to assist in box qty multipliers etc.

Basically I guess I need to find a way to have the script treat a blank field as zero to stop the NaN issue occurring.

**Comment by philcon93** [comment]
I'll have a chat with the team to see they can help out with this issue :)

**Comment by GerryFort** [comment]
Thanks @philcon93 !
