### ISSUE TITLE
Schema Tags — Let's do a full review

### ISSUE THREAD

**Issue by brandonsheppard** [NetoECommerce/Skeletal#53]
There have been a few schema issues lately—let's do a full review.

There are also probably a bunch of optional ones that we should be adding.

**Comment by curtiswilkinson** [comment]
Should I be looking into completely reworking it and using the JSON format for this? Or are we mostly just interested in ensuring we are utilising it fully?

**Comment by brandonsheppard** [comment]
Nah—JSON isn't an option for much of the data so let's keep the implementation as-is for now. Most important thing is to find if there is anything implemented incorrectly or omitted entirely.

**Comment by curtiswilkinson** [comment]
General Website:

- Local Business - Can't be done due to the way we handle addresses in the software (needs segregated postcode/city/state)
- Site Logo https://developers.google.com/search/docs/data-types/logo
- Social Profile Links https://developers.google.com/search/docs/data-types/social-profile-links
- Breadcrumbs  https://developers.google.com/search/docs/data-types/breadcrumbs'
- Corporate Contacts https://developers.google.com/search/docs/data-types/corporate-contacts

Product page and thumbnails:

- Product Description (should likely be excluded from thumbnails, but list.template.html could post [@subtitle@] to this)
- PriceValidUntil attribute for promotional prices (promo end)
- Product Brand


Blog thumbnails and default page: https://developers.google.com/search/docs/data-types/articles

- Headline (possibly only accepted for NewsArticle)
- Author (person schema)
- description
- URL is incorrect on te thumbnail
- publisher
- date published
- logo

**Comment by craigblunden** [comment]
Breadcrumbs merged here, needs to be applied to default and product page templates
https://github.com/NetoECommerce/Skeletal/pull/146

**Comment by brandonsheppard** [comment]
@curtiswilkinson This is great, thanks!

**Comment by brandonsheppard** [comment]
New issue to implement these findings here: https://github.com/NetoECommerce/Skeletal/issues/151
