### ISSUE TITLE
Reward Earned missing from onepage.template.html

### ISSUE THREAD

**Issue by dalerodgie** [NetoECommerce/Skeletal#91]
When a rewards program has been set up, the customer should be able to see the rewards points they have earned for their order.

This is from the documentation:

![png base64e9cc3fcb73aa0d10](https://cloud.githubusercontent.com/assets/7511456/11353748/c02be546-9291-11e5-8a18-b47ba11c610d.png)

https://www.neto.com.au/article/how-does-the-rewards-loyalty-points-system-work

**Comment by curtiswilkinson** [comment]
I was doing this up so we could add it into skeletal, however I've noted that freshly installed skeletal HAS the code to show this, as does the evo.neto.com.au site that originally raised this


	
<div class="well">
<h4>
Rewards Earned 
</h4>

<table cellpadding="4" cellspacing="0" width="100%" border="0">

	<tr><td valign="top" width="90%"><strong>[@vprogram_title@]</strong><br />
	[@vprogram_subtitle@]</td>
	<td valign="top" nowrap="nowrap">

	[@reward_points@]pts

	[@reward_amount@]

	</td></tr>

</table>

</div>
	

I am unsure why it's not actually DISPLAYING, this will require more investigation

**Comment by dalerodgie** [comment]
The rewards code is in `cart/includes/cart_items.template.html` not `onepage.template.html`

**Comment by curtiswilkinson** [comment]
cart_items is the AJAX template loaded up the top right of the checkout, it can't be placed into onepage.template.html because it needs to be hit with an AJAX reload when the shipping options are changed, because depending on the program it needs to factor in the shipping cost to calculating the points
![cart_items](https://cloud.githubusercontent.com/assets/12440573/11382970/b652c232-9350-11e5-932c-1716d9de26c8.png)

**Comment by brandonsheppard** [comment]
This was just set up incorrectly—forget about it!
