### ISSUE TITLE
Account Update Contact Detail Page

### ISSUE THREAD

**Issue by craigblunden** [NetoECommerce/Skeletal#97]
`/_myacct/edit_account#contact`

Postcode is limited to 4 characters, not useful for international countries.

`getlocation()` function needs to be changed the following line is restricting it to 4 characters:

```
zip.cvalue = zip.value = zip.value.replace(new RegExp('\\D','g'), '').substr(0,4);
```

I don't see why this is necessary and could likely just be removed if country != AU?

**Comment by brandonsheppard** [comment]
I vote we simply remove the character limit completely. Doesn't make sense to enforce validation on the account page and not on the cart page:

![](http://design.neto.com.au/assets/uploads/https___dev-brandon_neto_com_au__mycart_ts_1451524012180521_fn_payment_1C34B74D.png)

What happens if you are editing an address that already has > 4 characters in it's post code? Does it truncate the excess on save? Seems pretty silly.

Let's just kill it.

**Comment by brandonsheppard** [comment]
Fixed in https://github.com/NetoECommerce/Skeletal/pull/144
